### PR TITLE
93322128 release style guide

### PR DESCRIPTION
**Pull request by djvern**

### CODE REVIEW

**Comment by djvern** [comment]
@alexbridge instructions to manually test the front-end:

- Switch to the backend style guide branch (93322128_release_style_guide)
- Do a fresh install:
  - cd drupal
  - chmod 755 sites/default
  - drush si openevent --account-name="admin" --account-pass="admin" -y
  - drush en master -y
  - drush master-execute -y
- Login and add a style guide page and add some content, including an image. Add the page to the menu and publish
- Change permissions for anonymous and authenticated user to:
  - View published content 
  - Access the resource node
  - Access the resource paragraphs item
  - Access the resource file

- Pull down the front-end release branch (https://github.com/Southbank-Centre/southbankcentre.org-style-guide/tree/release-0.0.0)
- Edit the grunt file as required and run grunt serve

You should see the page at localhost:9000/nid. If you see a broken link for the image then it means you're having the same issue I am...

**Comment by alexbridge** [comment]
@djvern Drupal is warning me about the following missing modules:

* Double_field
* Htmltidy
* Menu_firstchild

I know you don't want to include Htmltidy in this repo: what about the others?

**Comment by djvern** [comment]
@alexbridge sorry I missed the 'drush make local-openevent.make -y' step above - have added now. It should download those modules for you as they are currently in the drupal-org.make file (to be moved to a SC make file later)

**Comment by djvern** [comment]
@jorgelopezlago have just assigned this to you in Alex's absence. The tests are passing for me in Sauce Labs now but please pull and double-check yourself.

**Pull request closed without merging**
