### PR TITLE
OE profile

### PR DESCRIPTION
**Pull request by tassosk-cogapp**
People,
this pull request is affecting everyone as it changes the codebase that we will have into the repository. The pull request is assigned to @jorgelopezlago but I would like your help (@samueljmurray, @djvern, @alexbridge) to see if everything works correctly.

The process to get it working on your local dev machine is:

1. Checkout the repository
2. Create a `local.settings.php` with your settings in drupal/site/defaul (do not symlink, create the actual file)
2. Run `cd drupal`
3. Run `drush make local-openevent.make -y`
4. Run `drush si openevent --account-name="root" --account-pass="root" -y`
5. Run `drush master-execute -y`
6. Run `drush fra -y`

Thank you.

T

**Additional information**

- After running `drush si` you re-set permissions to `/sites/default` with `u+x`.

### CODE REVIEW

**Comment by samueljmurray** [comment]
Hey Tassos,

Its looking good. A couple of things I encountered while installing:

- Drupal 7.35 installs rather than 7.36
- field_ui is enabled even though it is only set to install within the 'dev' scope in the master config. It installs even if you set the scope to be 'staging' or 'live'
- The Ember theme isn't installed, though the description of the story states that it will be

**Comment by tassosk-cogapp** [comment]
Hi @samueljmurray, so we can have a record of our conversation from the hangouts:
- field_ui all all *_ui modules are installed as a dependency on the profile. This is an open discussion on the story spec and is pending a final decision. 
- The Ember theme is a new dependency from CMSv1 so I did mark it as (new) and did not include it here. It will be addressed when the rest of the (new) dependencies are addressed.

Your first point certainly sounds like a bug and I will investigate.

**Comment by samueljmurray** [comment]
@tassosk-cogapp I've just found that the first issue (wrong Drupal version installed) isn't an issue with the code, it was a mistake in my local settings file

**Comment by alexbridge** [comment]
Everything installed correctly for me (using Drush v6.6.0) following the instructions above.

Most tests passed (though NB the tests expect a credentials of admin/admin, rather than root/root as in the instructions above). This was with the exception of:
* The Frisby tests, which have a known issue due to permissions
* The following tests for Events:
  1. WOW CMS can create a minimal event page
  2. WOW CMS can create a full event page
  3. WOW CMS does not allow an Event to have one of its child Events assigned as a parent

NB Less essential, but these tests should also be renamed so that they don't reference WOW any longer.

**Comment by tassosk-cogapp** [comment]
An update to 7.x-2.5 was released today for the feature module so I updated that too.

**Comment by samueljmurray** [comment]
@alexbridge I've updated the event tests with various changes and fixes - would you be able to pull the latest changes down and run the tests to see that they work?

**Comment by alexbridge** [comment]
All tests are now passing for me. Huzzah!

**Comment by samueljmurray** [comment]
Great. I'm happy for this to be merged when everyone else is

**Comment by tassosk-cogapp** [comment]
+1 from me.

**Comment by alexbridge** [comment]
+1

**Comment by samueljmurray** [comment]
It's strange - why has the contents of humans.txt been replaced with HTML?

@jorgelopezlago I agree that the OE Event profile shouldn't include a humans.txt with our details in it. But this repo is designed to contain both the OE Event profile and our implementation of it, so I think we should leave it in the repo. At some point we will migrate the OE Event distribution into its own repository, and at that point we would not include the humans.txt file

**Comment by tassosk-cogapp** [comment]
Two issues:

- I removed humans.txt as @jorgelopezlago suggested.
- git does not commit empty directories so an empty file is used until a custom module is added.

**Comment by samueljmurray** [comment]
@jorgelopezlago is the dblog override something we could do in the master.conf file on the dev and staging scopes instead of the profile?

**Comment by jorgelopezlago** [comment]
@samueljmurray yes, we can do that fiddling on master.conf.

**Comment by jorgelopezlago** [comment]
@samueljmurray 
I don't think it is a good idea to mix OE repo and our implementation of it. We should keep them separated.

**Comment by samueljmurray** [comment]
@jorgelopezlago I agree we should keep them separate, but in that case we'll need to create a new repo for the Open Event distribution and migrate this work into it, because this repo is for our CMS.

We'll also need to define processes for updating the OE profile and how those changes are moved into our CMS

**Comment by tassosk-cogapp** [comment]
@jorgelopezlago I addressed all comment bar the addition of new modules and themes (navbar and ember). These were not included they were new dependencies. Should these go in a new story or add them in place as part of this story?

**Comment by jorgelopezlago** [comment]
Is there any use for the *patches* folder now? All patches should be loaded form D.O.

**Comment by jorgelopezlago** [comment]
**drupal-org.make**
1) Change line 7 with: "; To define a specific module version (eg ctools 1.4) and place it in a"
2) Add a comment line for each patch to describe the reason for it or what it does
3) Change line 19 with: ";   projects[ctools][patch][1023606] = "http://drupal.org/files/issues/1023606-qid-to-name-6.patch""

**Comment by jorgelopezlago** [comment]
**openevent.profile**
Why hard codding the admin_account?
```$form['admin_account']['account']['name']['#default_value'] = 'root';```

**Comment by jorgelopezlago** [comment]
**Missing components from the profile**
I have noticed the following missing components form the profile:
- Navbar
- Better formats
- jQuery update
- Ember (theme)
Reasons to include them:
1) Responsive admin interface (a la D8): Ember + Navbar + jQuery (this will require some extra third party libraries as well).
2) Better formats is paramount to manage the text formats in a reasonable way for the content types.

**Comment by jorgelopezlago** [comment]
**openevent.install**
Replace *Seven* with *Ember* as admin theme.

**Comment by jorgelopezlago** [comment]
**OE Event**
1) Many fields are prefixed with *event*. That makes them non shareable (I guess that is the intention) with other content types. Without entering on the discussion whether is better to share or not to share fields in Drupal, what is the reason for this? The following fields seem good candidates for re-usability to me:
 - field_event_age_range
 - field_event_start_time
 - field_event_end_time
 - field_event_duration

2) Date fields: the proposal to keep them as a single field was to use a common pattern with great flexibility for other institutions to use. It will be more complicated to map, but it is not reasonable to impose such limitation on an product that will be shared by many.

3) Why is *event class* required? Schema.org can accept an event that is just an event, without any other denominations.

4) Event class description: add some reference to the implications of this choice (Schema.org event type). A generic note will do for now.

5) Event parent: add some description with explanation about the limits to choose parents. This is the core functionality of this content type and the whole events system and it deserves some explanation. We could add some explanation to the content type *Explanation or submission guidelines* as a better place to provide general description of capabilities and process. 

6) Event type: this is a multiple choice field. What would be the use case for it?

7) Age range: I see that the validation choice and explanation has been added based on the limited information in Schema.org, but it seems like a estrange way of expressing age groups.  he following notation makes sense to me:
 - 12 (only 12 years old)
 - -12 (12 or less)
 - 12-16 (between 12 and 16 years old)
 - 18+ (18 or older)

8) View *Event Parent*: the access control is set to "Permissions|View published content" but there is no filter in the view for only published content. As we may want to allow to create relationships to unpublished events I think we should define a different access control. Possibly other permission.

9) View *Event Parent*: could anyone explain me the logic behind the contextual filters default values for this view?

*Note for the future: we may need to display the fields conditionally based on the value of the event class field.*

**Comment by alexbridge** [comment]
Regarding (7) in the previous comment, the notation '-12' for '12 or less' isn't something I've ever seen before, and I don't know how intuitive it'll be for editors. Alternatives I have seen in use:
* 0-12
* < 12

I prefer the first one because it's immediately understandable, and compatible with the syntax suggested by schema.org while avoiding the awkward '12-' representation.

**Comment by alexbridge** [comment]
Regarding (1) - I believe these were made event-specific because it felt like our implementation of events covered everything (festivals, series etc. in addition to events) that would ever need to specify an age range, duration etc.

**Comment by samueljmurray** [comment]
1) I agree with Alex and can't think of anywhere else we'd want to reuse them

2) I'm not sure I understand what you mean. What are the downsides of having start and end date as 2 separate fields?

3) I think assigning every event to a class would help reduce confusion. I imagined ours would be 'Festival', 'Series' and 'Performance', but obviously that's a different discussion.

4) I'm not sure we have decided on any implications of choosing a class at this point. We should think about working out a way to allow events with particular classes to be output as event sub-types, (e.g. festival) but we'd need a mechanism for inputting this mapping, which we don't have yet.

5) I'll add a more detailed description to this field.

6) This is the same as the Event Type field that exists in CMS v1. The difference is this field allows multiple terms to be selected. I don't see why it shouldn't be a multi-select field, the same way that multiple art forms can be selected in the CMS for the current SC website.

7) Good point, although I agree with Alex about not having an 'And under' syntax. So how about we implement the following 2 possibilities: '0-12' and '18+'

8) Could the permission here just be 'Administer content'?

9) The 'Content: Parent' contextual filter prevents an editor from creating a direct circular reference. E.g. if node 1 is a parent of node 2, an editor cannot select node 2 as a parent of node 1. The 'Content: Nid' contextual filter prevents an event being set as a parent of itself.

10) I disagree. We should create a new SC feature that installs the *Event class* and *Event type* terms, rather than installing them from the OE Event feature.

11) See 1.

**Comment by samueljmurray** [comment]
After discussion of (2): change start date and end date to be 1 field because it will allow more complex data representations (e.g. repeating events)

**Comment by samueljmurray** [comment]
After discussion of (4): improve description of *Event class* and *Event type* fields and taxonomies

**Comment by samueljmurray** [comment]
After discussion of (7): possible values will be 'N', 'N-N', 'N+'

**Comment by samueljmurray** [comment]
After discussion of (8): remove access restrictions on the view

**Comment by samueljmurray** [comment]
After discussion of (10): this will be covered by [#91354818](https://www.pivotaltracker.com/story/show/91354818)

**Comment by samueljmurray** [comment]
After discussion of (5): improve description of Event parents

**Comment by tassosk-cogapp** [comment]
I did the changes that we have discussed. Please @jorgelopezlago review.

**Comment by tassosk-cogapp** [comment]
My exact sequence of commands for anyone interested where:
```
git checkout -b OE_profile_amends_tassosk
```
Did my changes and committed everything.

```
git rebase OE_profile
git checkout OE_profile
git merge --ff-only OE_profile_amends_tassosk
git push
git branch -d OE_profile_amends_tassosk
```

**Comment by jorgelopezlago** [comment]
**Text formats**
*Limited HTML* is a legacy form an specific case from the CMS v1 (WOW flavour). We do not need it in CMS v2.
Review the permissions as only users with the administrator role can use them. The following should be configured out of the box:
- Iframe HTML: administrator, authenticated
- Filtered HTML: administrator, authenticated
- Full HTML: administrator
- Plain text: all roles

**Comment by tassosk-cogapp** [comment]
In regards to (2) since Pivotal Tracker is open it would have been nice to provide to the public a way to get more involved. Having a reference to our internal tracker in my mind would encourage more active involvement if someone was looking for it.

**Comment by jorgelopezlago** [comment]
@tassosk-cogapp And how would the public know where to look for that issue number?
I think that when we release everything on Github, properly, the issue tracker of Github will take over, just out of pure convenience.

**Comment by jorgelopezlago** [comment]
**Default permissions on openevent.install**
We do not have ANY permissions for *anonymous* and *authenticated* roles.
Add the same permissions than the *Standard* profile out of the box. They will be updated accordingly to our use case:
```
// Enable default permissions for system roles.
  $filtered_html_permission = filter_permission_name($filtered_html_format);
  user_role_grant_permissions(DRUPAL_ANONYMOUS_RID, array('access content', 'access comments', $filtered_html_permission));
  user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('access content', 'access comments', 'post comments', 'skip comment approval', $filtered_html_permission));
```

**Comment by jorgelopezlago** [comment]
**Features duplication**
The architecture we have makes all content type features to depend on *oe_components* as they will be extended through paragraphs provided by the later. Why do we need a separate feature *oe_fields/oe_shared*? This second one just brings one more dependency to all the content types features without any advantage as the contents of this feature could be easily included in oe_components.
I think we must merge the content of *oe_shared* into *oe_components* and reduce the dependencies amongst our other features. This construction will make *oe_components* a stand alone feature with a set of useful fields, settings and paragraphs that could be used by anyone.

**Comment by tassosk-cogapp** [comment]
Good point @jorgelopezlago, openevent.install is a direct port of the festival profile and as such it only contains what festival had. I agree that we should provide sensible defaults to users of Open Event. I have added a [story](https://www.pivotaltracker.com/story/show/92913946) to discuss:
- are filters going to be part of .install the same way it is on standard profile
- what roles can we create automatically
- what kind of permissions would these roles have.

We can follow up discussion of this issue there. I have placed that story as non-estimated but in the next sprint.

**Comment by tassosk-cogapp** [comment]
@jorgelopezlago Pivotal Tracker is public which means that it is public and open to the public. The public would know where to look with stories such as [this](http://digital.southbankcentre.co.uk/open-agenda-weve-made-pivotal-tracker-public/).

**Comment by samueljmurray** [comment]
@jorgelopezlago yes I agree with packaging all of the 'shared' field bases and the paragraph bundles together into one feature called **OE Components**

**Comment by djvern** [comment]
Let's do it. I can do this work this afternoon, as I was ready to rebase
the image work back into the OE Profile branch - I'll hold off until I've
consolidated the 2 features, if we're all agreed?


............................................................

*Dave Vernon*
Digital developer

*Southbank Centre*
Belvedere Road
London
SE1 8XX
M: 07734 663 277

<http://www.southbankcentre.co.uk>

**Comment by jorgelopezlago** [comment]
**Paragraph Quote**
Why do we have a field_quote that is basically the same that field_text? We could reuse it in this context.
Also it uses *Limited HTML* filter, which is deprecated and to be removed.

**Comment by jorgelopezlago** [comment]
**OE components**
None of the components fields have descriptions to help editors to understand what to do with them or the type of content expected.

**Comment by djvern** [comment]
@jorgelopezlago we decided in the end not to make field base names too generic - from the front end point of view this was to allow the view templates to keep some meaning - eg field_quote is better semantically for describing the data than field_text. However the JSON data is generally wrapped in semantic html tags and relevant classes, so we could change this if required. Below is an example of the quote component view template:
```<div class="pullquote-container">
  <q data-ng-bind-html="paragraph.field_quote.value"></q>
  <div>{{ paragraph.field_quote_attribution }}</div>
</div>
```

**Comment by djvern** [comment]
@jorgelopezlago I'll add some help text in for the components now.

**Comment by samueljmurray** [comment]
Hi everyone, I've made amends to the OE Event feature after @jorgelopezlago 's review (see commits above this comment)

**Comment by djvern** [comment]
@tassosk-cogapp the above commits are ready to be reviewed. Changes are:
- renamed OE Content Components feature to OE Components
- removed Limited HTML text filter
- renamed OE Fields to OE Shared
- added Image paragraph bundle to OE Components
- added Image field to OE Event
- Renamed OE Components (embeds) and added help text
- Consolidated OE Shared and OE Components into one 'OE Components' feature
- Removed OE Fields from master.conf
- Automated tests for Image

Please run the automated tests one suite at a time until we fix the frisby bug - eg:
```
protractor conf.js --suite event
```

**Comment by tassosk-cogapp** [comment]
@djvern I have updated the conf.js in my elastic search story last time to make it more modular. Changes were:

```
  params: {
    url: 'http://api.wow.southbankcentre.co.uk',
    user: 'admin',
    pass: 'admin'
  },
```
and 
```
  // Options to be passed to jasmine-node.
  jasmineNodeOpts: {
    // If true, print colors to the terminal.
    showColors: true,
    // Default time to wait in ms before a test fails.
    defaultTimeoutInterval: 30000
  },

  // function to run before the tests - logs the browser into the CMS
  onPrepare: function() {
    global.dvr = browser.driver;
    global.frisby = require('frisby'); // include Frisby.js for JSON tests

    dvr.get(browser.params.url + '/user/login');

    dvr.findElement(by.id('edit-name')).sendKeys('admin');
    dvr.findElement(by.id('edit-pass')).sendKeys('admin');
    dvr.findElement(by.id('edit-submit')).click();

    // Login takes some time, so wait until it's done.
    dvr.wait(function() {
      return dvr.getCurrentUrl().then(function(url) {
        return /user/.test(url);
      });
    });

    // Testing on Angular site or not
    global.isAngularSite = function(flag){
      browser.ignoreSynchronization = !flag;
    };
  },
```

You can view the changes [here](https://github.com/Southbank-Centre/southbankcentre.org/tree/89903536_drupal_import_from_elastic/test/functional). Could please update the files accordingly.

**Comment by samueljmurray** [comment]
@jorgelopezlago @alexbridge @tassosk-cogapp @djvern we should be ready to merge once everyone has tried out running the tests and they pass successfully. Could everyone try running the tests? If you look at my last few commits you'll see how you can run them all together. The mechanism for running the suites one-by-one isn't ideal, but it gets around the problem for now.

**Comment by alexbridge** [comment]
All tests pass for me.

NB I had to upgrade to node 0.12 in order for it to work for me

**Comment by djvern** [comment]
The tests all pass for me too after upgrading to node 0.12 and running
$ node run_suites_synchronously

**Pull request merged**
