### PR TITLE
91354680 oe event

### PR DESCRIPTION
**Pull request by samueljmurray**

### CODE REVIEW

**Comment by tassosk-cogapp** [comment]
Hi Sam, good work. 

Some comments below:

- The age field is set as size 60 but after doing a normal install and going through the actual node edit form it goes all the way through the right-hand side of the page. Is that desired? Do we know why that is happening?

- I think it would be a benefit for the user to actually have a link to the schema.org property that each field references. For instance the age group help text should have a link [here](https://schema.org/typicalAgeRange). Wherever applicable. If a user enters the correct value she is presented with an error message. I would add some reference to schema.org there too.

- I have created a two nodes (1 and 2). Whenever I try to make 1 the parent of 2 I get the following error: *The referenced entity (node: 1) is invalid.*.  I get the same error for any subsequent nodes I add and try to reference node/1. Associations from node/2 onwards seem to be working fine.

- Is there a way to currently allow all day event? Submitting with only the date field added it gives back an error (*not matching expected format*).

**Comment by samueljmurray** [comment]
Thanks @tassosk-cogapp 

1) This is being caused by the style for text fields within 'vertical tab' field groups, which is being set by CSS from the Fieldgroup module. They're width style is being set to 100%. I think we can leave it as it is for now, but it's something we could fix at a later date if it's causing problems.

2) Yes I agree. I'll add that information to the field descriptions, and a bit more information to the content type description too.

3) That's odd. I'll try to recreate the issue with a fresh install.

4) I'll enable date_all_day and set the event start and end fields to allow 'All day'

**Comment by samueljmurray** [comment]
@tassosk-cogapp I've made those changes - could you review and merge if you're happy

**Comment by tassosk-cogapp** [comment]
It is looking good @samueljmurray.

**Pull request merged**
