### PR TITLE
87009206 style guide

### PR DESCRIPTION
**Pull request by samueljmurray**
@tassosk-cogapp please check out and run the style_guide test suite too. Note that I've put the SC Style Guide feature into the openevent profile for now. It will be moved out when [#92518920](https://www.pivotaltracker.com/story/show/92518920) is implemented.

### CODE REVIEW

**Comment by tassosk-cogapp** [comment]
@samueljmurray the site currently does not build correctly through the make file. There are modules missing or not installed. The process I followed is:

```
git clone repository
cd repository/drupal
drush make local-openevent.make -y
drush si openevent --account-name="root" --account-pass="root" -y
chmod 777 sites/default/files
chmod u+w sites/default/
drush master-execute -y
```
It fails there because of missing dependencies.

Can you make sure that:
- the `style_guide` feature and `double_field` module are added in openevent.info and master.conf.php (we use alphabetical sorting so please make sure you take into account)
- the `double_field` module is added in `drupal-org.make` according to the instructions of that script (within the openevent profile)

Push your changes and let me know so I can review again.

**Comment by tassosk-cogapp** [comment]
Also there is an update of restWS to 7.x-2.4 we can do that also.

**Comment by samueljmurray** [comment]
@tassosk-cogapp I've made those changes so it should install properly now

**Comment by djvern** [comment]
@tassosk-cogapp @samueljmurray it all installs fine for me now :-)

**Comment by samueljmurray** [comment]
@tassosk-cogapp the first one is failing because the cleanup function logs back in as the admin user, and it needs to use the admin user and password you define in the conf.js params, so i'll make that change now.

I'm not sure about the issue with the menu_api test, but it may be caused by the first tests not cleaning up properly

After I've commited you'll need to do a fresh install

**Pull request merged**
