### PR TITLE
93322128 release style guide

### PR DESCRIPTION
**Pull request by djvern**
@jorgelopezlago sorry I've just recreated this pull request as I had to rebase against develop to get Sam's Saucelab tunnel settings - please pull this branch again and run the tests...

### CODE REVIEW

**Comment by jorgelopezlago** [comment]
We must document the requirements for this to work, specifically the need for tidy to be installed as an executable, not as a php extension.
We must implement hook_requirements() in the install file of the module/feature (https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_requirements/7).

When the tidy executable is missing there is one test that fails without apparent reason.

**Comment by jorgelopezlago** [comment]
The *designer* role doesn't seem to have access to the JSON view of the style guide nodes.

**Comment by jorgelopezlago** [comment]
Deprecated function error message when viewing a style guide node. It is a message from PHP with DEBUG level.

Deprecated function: Function split() is deprecated in htmltidy_run() (line 424 of /home/jorge/Copy/sites/southbank/styleguide/www/drupal/sites/all/modules/contrib/htmltidy/htmltidy.module).

**Comment by jorgelopezlago** [comment]
This backend component doesn't make much sense without the front end. We can either tie them together or provide better view of the styles in the Drupal backend so this feature makes sense independently.

**Comment by tassosk-cogapp** [comment]
I agree with @jorgelopezlago comments. A new story should be added to make the style guide an isolated self-contain module for SC distribution and tackled when we get at that point. 

The style guide app has taken a good chunk of time to complete and we should focus on moving forward.

**Comment by samueljmurray** [comment]
@jorgelopezlago I don't think this feature needs to make any sense without the front-end. In fact, I doubt any of the 'SC' features will make sense without the front end, and I don't think we should put any work in to change that unless there is a specific need to.

**Comment by djvern** [comment]
@jorgelopezlago I've added some permissions to the designer role to access the JSON resources now (node, paragraph item and file)

**Comment by jorgelopezlago** [comment]
@djvern Installation requirements moved to a separat story, as agreed: https://www.pivotaltracker.com/story/show/94386710

**Comment by jorgelopezlago** [comment]
We must discuss the way SC functionality is packed and document or relate it to a front end implementation. Moved discussion to a specific story: https://www.pivotaltracker.com/story/show/94387380

**Comment by jorgelopezlago** [comment]
Deprecated function issue raised as a separate bug: https://www.pivotaltracker.com/story/show/94387448

**Pull request merged**
